### PR TITLE
Added framework for Testing Extension

### PR DESCRIPTION
**Pull request by mattiascibien**
With this PR we are going to have:

 - A testing framework that will be called using `npm test`
 - Code Coverage using [codecov.io](https://github.com/dlang-vscode/dlang-vscode). Data is pushed using travis.ci (appveyor is kept for unstable builds)

### CODE REVIEW

**Comment by LaurentTreguier** [comment]
Hi there, the conflicts with master are now resolved.
I've tried checking out this branch and running `npm test`, however after opening a VSCode window it leaves me with `Error: Cannot find module '[...path to dlang-vscode...]/dlang-vscode/test'`. Do you know where that can come from ?

**Comment by LaurentTreguier** [comment]
Nevermind, reading the docs on how to run tests should always be done beforehand

**Comment by LaurentTreguier** [comment]
@mattiascibien what does everything in `test/index.ts` do ? When creating a new typescript extension with `yo code`, `test/index.ts` only contains this:
```typescript
//
// PLEASE DO NOT MODIFY / DELETE UNLESS YOU KNOW WHAT YOU ARE DOING
//
// This file is providing the test runner to use when running extension tests.
// By default the test runner in use is Mocha based.
//
// You can provide your own test runner if you want to override it by exporting
// a function run(testRoot: string, clb: (error:Error) => void) that the extension
// host can call to run the tests. The test runner is expected to use console.log
// to report the results back to the caller. When the tests are finished, return
// a possible error to the callback or null if none.

var testRunner = require('vscode/lib/testrunner');

// You can directly control Mocha options by uncommenting the following lines
// See https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options for more info
testRunner.configure({
    ui: 'tdd', 		// the TDD UI is being used in extension.test.ts (suite, test, etc.)
    useColors: true // colored output from test results
});

module.exports = testRunner;
```

**Comment by LaurentTreguier** [comment]
@mattiascibien With the 5 last commits I pushed, there are now very basic tests for Dfmt.
For this I changed Mocha's `ui` from `tdd` to `bdd`, as I find it better suited to testing behaviors of the extension.

`extension.test.ts` contains global `before` and `after` functions to manually start and stop the extension, as well as taking care of a temporary file that is used for the tests themselves.
For now `dfmt.test.ts` simply has tests to check different identations (tabs, 2 spaces, 4 spaces and 8 spaces).

There are a few files in `test/d/dfmt` that are used for the test, but the tests are done in a temporary file in order not to modify these files since the way of testing here is to direct VSCode to open up a file, format it and then looking at the result.

EDIT:
The tests on Travis and Appveyor will need to be updated to install dmd and dub, and right now they can't start the extension because the SDlang extension is not installed.

**Comment by mattiascibien** [comment]
Have you tried

    code --install-extension LaurentTreguier.sdlang

This should make possible to install the extension using the cmdline.

EDIT: Not sure on how to do that with travis and appveyor

**Comment by LaurentTreguier** [comment]
Prior to executing the tests, VSCode is downloaded into `.vscode-test`. With this it should be possible to install it, but that would require doing the tests twice and skipping them the first time when `LaurentTreguier.sdlang` isn't installed

**Comment by LaurentTreguier** [comment]
@mattiascibien after much trial and error, Appveyor now correctly runs the tests. Now only the Travis build remains.

What I did regarding `sdlang-vscode` is simply downloading it and putting it in `~/.vscode/extensions` in both the Travis and the Appveyor builds.

**Comment by LaurentTreguier** [comment]
@mattiascibien do you know what the difference between `
continuous-integration/travis-ci/pr` and `continuous-integration/travis-ci/push` is ? One of them is now fixed but the other still fails...

EDIT : nevermind, redoing the build yielded no failure.

**Comment by LaurentTreguier** [comment]
Also, I forgot to say that I removed `osx` from `.travis.yml`'s OS's because the Travis lint tool stated that the `node_js` language is not supported on macOS

**Comment by mattiascibien** [comment]
You are the best indeed. I guess we can soon close this.

Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [dlang-vscode/dlang-vscode] Added framework for Testing Extension (#37)
Da: LaurentTreguier
A: dlang-vscode/dlang-vscode
CC: Mattias Cibien ,Mention


Also, I forgot to say that I removed osx from .travis.yml's OS's because the Travis lint tool stated that the node_js language is not supported on macOS

**Pull request merged**
