### PR TITLE
Symbol navigation, linting upgrade and more config

### PR DESCRIPTION
**Pull request by LaurentTreguier**
@mattiascibien This new update's main feature is symbol navigation. Using`dscanner --ast`, the extension gets the information it needs to provide document and workspace symbol navigation. While DMD has a `-X` switch which outputs JSON directly with exactly what's needed, it still has to compile files, and works only as a side effect of compiling, so I haven't found a way to really use it.
Linting now uses `dscanner --report` instead of `dscanner --styleCheck`. It produces a JSON that makes for easy usage, and provides precise categories of errors and warnings instead of simply `[error]` and `[warn]`. I'm thinking about using this later for providing [code actions](https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings).
DCD and dfmt also get configuration options that correspond directly to the command line options, to enable using a custom listening port for DCD and tweaking formatting.

### CODE REVIEW

**Comment by mattiascibien** [comment]
@LaurentTreguier whoa... that's really impressive. :+1:

**Comment by LaurentTreguier** [comment]
@mattiascibien I've noticed that linting  doesn't work on Windows due to `dscanner --report` not escaping backslashes in paths, which makes for unparsable JSONs. I've opened up an [issue](https://github.com/Hackerpilot/Dscanner/issues/365) about it, it should be fixed in a future release

**Comment by mattiascibien** [comment]
@LaurentTreguier if it is ok now I will merge it with master

**Comment by LaurentTreguier** [comment]
@mattiascibien I think it's ok now. The issue about dscanner has been addressed and I have had no further problems with this version

**Comment by mattiascibien** [comment]
@LaurentTreguier ok... I'll merge now and publish the new version ASAP.

**Pull request merged**
