### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by LaurentTreguier**
@mattiascibien Now that #12 is merged, I looked and dug up what I had worked on at the end of July.
Here are the changes :
- dub packages used by the extension are now built in release mode instead of the default debug mode
- thanks to DCD, documentation is shown upon hovering on words
- there is an explorer menu option to manually  import a directory for DCD completion
- dub fetches and builds operations are now logged in an OutputChannel, like it should have been from the start
- a [Dustmite](https://github.com/CyberShadow/DustMite) command is available to automatically launch Dustmite when  facing a compilation error ; it tries to build the project and lets the user select the error line to stick to when reducing code
- extension dependency for SDLang support
- various fixes

### CODE REVIEW

**Comment by mattiascibien** [comment]
@LaurentTreguier ignore the checks on appveyor, I am still working on that

**Comment by mattiascibien** [comment]
@LaurentTreguier I'll push 0.8.1 and then work on this.

**Comment by LaurentTreguier** [comment]
@mattiascibien :+1:

**Comment by mattiascibien** [comment]
@LaurentTreguier I have merged main back into this. Can you check if it is right?

**Comment by mattiascibien** [comment]
@LaurentTreguier I get the error `dlang-vscode.dlang failed to activate. Reason: unknown dependency LaurentTreguier.sdlang`. is it available?

**Comment by LaurentTreguier** [comment]
@mattiascibien It should be... According to [the docs](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_fields), `extensionDependencies` in the manifest is an array of extension id's:

> An array with the ids of extensions that this extension depends on. The id of an extension is always ${publisher}.${name}. For example: vscode.csharp.

**Comment by mattiascibien** [comment]
@LaurentTreguier for debugging I guess it must be installed before launching the development host. Installing the whole thing fixed debugging.

**Comment by mattiascibien** [comment]
@LaurentTreguier this is bad and not our fault i guess:

```
Dub build : dfmt
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(322,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(328,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(348,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
dmd failed with exit code 1.
Dub build : dscanner
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(322,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(328,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\package.d(348,13): Error: std.experimental.allocator.common.Ternary at ..\experimental_allocator-2.70.0-b1\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at C:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
```

The strange thing is that i get that error for every dub package of the extension but dcd-server is still running fine...

**Comment by LaurentTreguier** [comment]
@mattiascibien yes, I have encountered this as well... I think it's an upstream problem too. It's been a long time since the last DCD release, and not even one of the alpha versions seem to compile

**Comment by mattiascibien** [comment]
@LaurentTreguier then why is it running correctly then? :puzzled:

**Comment by LaurentTreguier** [comment]
@mattiascibien you probably still have the dcd client and server executables compiled with an older version of dmd... The extension simply tries to compile at startup in order to be sure it is compiled.

**Comment by LaurentTreguier** [comment]
@mattiascibien Maybe there should be an option to override the DCD, DFMT etc. executable paths to temporarily avoid this kind of problem ?

**Comment by mattiascibien** [comment]
Great idea.

**Comment by LaurentTreguier** [comment]
Now everything works fine if DCD is in the path or if the `d.tools.dcd.*` path options are correctly set

**Comment by LaurentTreguier** [comment]
As requested in #21, I added a small patch to be able to disable tools at will. This allows for easier handling of tools which are not compiling for now

**Comment by mattiascibien** [comment]
@LaurentTreguier I'll have a look into merging this and releasing the update ASAP.

**Comment by mattiascibien** [comment]
Pushe 0.9.0 https://marketplace.visualstudio.com/items?itemName=dlang-vscode.dlang

**Comment by LaurentTreguier** [comment]
Do you think the work should be done directly on `master` ? (since you deleted the `dev` branch)

**Comment by mattiascibien** [comment]
I suggest to go with git flow and feature branches if you'd like. Will be better even when I finally setup CI. I'll setup the development branch now. That was an error by my side

**Comment by LaurentTreguier** [comment]
> to go with git flow and feature branches

I'm not sure I understand what you mean by that ?

**Pull request merged**
