### PR TITLE
Start fixing problems using code actions

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This adds some code actions to VSCode to fix problems with the light bulb when a portion of code receives a warning lint from Dscanner. This PR follows #23 : since then the extension takes `dscanner.ini` files into account when it's present at the root of the workspace, but up until now it was necessary to edit the file manually and add the correct line to control which checks are enabled/disabled.

Now every lint in VSCode has at least one code action that modifies `dscanner.ini` to disable the corresponding check. Some checks also have a code action to fix the problem automatically :
- replacing deprecated `delete` keyword with `destroy()`
- replacing deprecated `alias a b` syntax with `alias b = a`
- imports sorting

Also, there is now a status bar item to create a default `.vscode/tasks.json` file easily, like some other extension do.

### CODE REVIEW

**Comment by mattiascibien** [comment]
@LaurentTreguier can you try to merge the latest master into this since I have merged some PRs?

**Comment by LaurentTreguier** [comment]
It's nice to see the CI go all green 😃

**Comment by mattiascibien** [comment]
@LaurentTreguier definetely. Tell me when you are confident with this so I will merge and release.

**Comment by LaurentTreguier** [comment]
@mattiascibien I'm pretty confident about it, I just tested it on Windows after developping it on Linux and it seems to work as intended.

**Comment by mattiascibien** [comment]
Ok... I'll merge tomorrow and start to plan the next release.

________________________________

**Pull request merged**
