### PR TITLE
Add basic autocompletion and formatting support

### LINKED ISSUE #1: DCD support?
Just noticed this project, very exciting!
Is there intent to support DCD for autocomplete and co?

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This PR adds some autocompletion support using [DCD](https://github.com/Hackerpilot/DCD) and should fix #1. It's not necessary to DCD installed though, only dub is required : t will automatically pull, build and use the latest version of DCD upon plugin activation (and warn the user if it's not installed).
It still lacks SDL dub file support, function documentation and such, but those may be coming soon.

EDIT : I also added a D logo and color for the visual studio marketplace
EDIT 2 : Now there is also a definition provider for the Go-to-symbol feature
EDIT 3 : Now with support for [DFMT](https://github.com/Hackerpilot/dfmt) formatting

### CODE REVIEW

**Comment by mattiascibien** [comment]
Hi laurent, thanks for your PR. As soon as I can I will check your PR and surely merge it because it is such a cool feature.

Have a nice day.

**Comment by mattiascibien** [comment]
@LaurentTreguier : what changes are you trying to include with the commits you added after my last post in this PR?

**Comment by LaurentTreguier** [comment]
Whoops, I kind of mechanically pushed changes I made without remembering it was in this PR... Sorry, my bad. These commits fix a few things, such as a bug happening at first run if none of the used dub packages were installed, some preliminary calltips for better completion, make use of path.join to have more secure file path handling, and a bit of clean up. I'll make another branch for further changes.

**Comment by mattiascibien** [comment]
@LaurentTreguier do not worry. Thanks for your great contribution. I swear I am going to check it asap and maybe move to a github organization of the whole thing.

**Comment by mattiascibien** [comment]
@LaurentTreguier is it safe to test and merge this PR or does the new changes require more improvements?

**Comment by LaurentTreguier** [comment]
I think it can be tested and merged, still with a lot of testing though; it may work on my system but there can always be surprises... The latest changes are mostly fixes for the original code, so it shouldn't need anything more to make it work as it is supposed to work (I think).

**Comment by mattiascibien** [comment]
@LaurentTreguier which os are you using?

**Comment by LaurentTreguier** [comment]
I developped it on Archlinux and tested it a bit on Windows 10.

**Comment by mattiascibien** [comment]
@LaurentTreguier I am actually trying your changes in Win10. Formatting is running fine but I can't seem to get suggestions with Ctrl+Space. dcd-server gets fired up correctly, however it is seem to be stuck on loading for ages. How long did it take to you for completion items to show up?

EDIT: i added a simple fn() function and it appears without problems by using f and pressing ctrl+space

Very nice work.

**Comment by LaurentTreguier** [comment]
Maybe one of my last changes didn't work... Where is your D installation directory ? Is it C:\D ? The server is supposed to add phobos directory to completions according to the OS. Are you only getting completions from your own code ?

**Comment by mattiascibien** [comment]
Yep... getting only them from my own project..
I have `C:\d\` as install dir and dub is in `C:\d\dub`

**Comment by LaurentTreguier** [comment]
I think I see the problem... In [server.ts](https://github.com/LaurentTreguier/dlang-vscode/blob/master/src/dcd/server.ts#L49) I try to match the platform with `windows` instead of `win32`. I must have forgotten to reboot and check if it worked...

**Comment by mattiascibien** [comment]
Tried on my local copy and now works like a charm... Would be nice to customize the phobos src dir via a config for guys which do not have dmd installed in the default directory... Anyway if we can fix this I will merge without problems. From my preliminary tests it seems that it is working pretty fine now. 

Do you agree if I move the package under an org and I give you write permissions? Obviously if you'd like to continue to work on this.

**Comment by LaurentTreguier** [comment]
Moving the package is fine by me. I'll try to make up some config options as you said. I will be a bit busy in the next two weeks or so, but I will definitly come back to it after that. I still have linting, Dfix and dub integration to do :smile:

**Comment by mattiascibien** [comment]
@LaurentTreguier do not worry about config for now. If you are busy I can just merge this PR and work on config files by myself. Meanwhile I will also add write permissions for you on this repo.

**Comment by mattiascibien** [comment]
I have merged the PR and added you as a collaborator.

**Pull request merged**
